### ISSUE TITLE
Nov 2017: 2 years with Docker, our stack & lessons learned

### ISSUE THREAD

**Issue by ahfeel** [docker-barcelona/speakers#11]
* **Title**: 2 years with Docker, our stack & lessons learned
* **Speaker**: Jérémie Bordier
* **Language**: en
* **Type**: 30-45 mins
* **Level**: standard
* **Tags**: devops

**Description**

After 2 years running in production with Docker, this has been a real journey. Figuring out how to make a robust production docker deployment is not easy and requires tradeoffs. No stacks are equals nor perfect, the ecosystem is pretty young and moving fast. Here's our shot to have something easy to work with, fast and agile.

**Speaker Bio** (optional)

CTO for a quite big e-commerce group, I've been coding and creating things for a while now :)

**Comment by dkapanidis** [comment]
Added to schedule https://www.meetup.com/docker-barcelona-spain/events/244113207/
