### ISSUE TITLE
Propposed talk for Docker Meetup (December)

### ISSUE THREAD

**Issue by doublebyte1** [docker-barcelona/speakers#12]
* **Micro-services through Docker: Tales from a Journey**: 
* **Joana Simoes**: 
* **Language**: (en )
* **Type**: (Lightning Talk 5-10 mins)
* **Level**: (advanced)
* **Tags**: (lessons learned, devops, micro-services)

**Description**
*In this talk I will share some experiences regarding the implementation of a micro-services architecture using docker, highlighting some things which worked for us, and describing some of the challenges we had to face along the way.
*

**Speaker Bio**
*Joana is a senior software engineer and architect at GeoCat, a company which develops Free and Open Source Software, in the field of Spatial Data Infrastructures.
She has been involved in the development of GeoCat Live, a cloud based solution for the automated deployment of spatial services. She is also the creator and maintainer of the Geonetwork official image on Docker hub.
*

**Comment by doublebyte1** [comment]
Hi @spiddy was this talk accepted? Just le me know, so that I can start preparing it :-)

**Comment by dkapanidis** [comment]
good to go 👍, I added your talk on the meetup

**Comment by doublebyte1** [comment]
@spiddy I think I will take more than 15 minutes for the talk... maybe 20-25 min, if that's ok. :-)

**Comment by dkapanidis** [comment]
Sure, you can do a full talk, we have time. I'll update the meetup

**Comment by dkapanidis** [comment]
done
