### ISSUE TITLE
Just Enough Docker

### ISSUE THREAD

**Issue by pchico83** [docker-barcelona/speakers#13]
* **Title**: Dockerizing Legacy Applications
* **Speaker**: Pablo Chico de Guzmán
* **Language**:es
* **Type**: Presentation 25-20 mins
* **Level**: standard
* **Tags**: devops, deployment
* **Description**: Docker is the dominant tool for containerizing applications. It is quite simple to start a new application using Docker and you see the benefits very soon. A different story is the challenge of migrating a legacy application to docker. Even if the app is not decomposed in different microservices or if you are far of making use of container cluster management tools like kubernetes or swarm, there is still a great value on containerizing your apps: local environment setup, ci automation, security or portability. We will cover this problem in detail and introduce the MTA (Modernize Traditional Applications) Docker Program.
* **Speaker Bio**: Pablo is Software Engineer @Docker where he is responsible of developing and maintaining Docker Hub and OSS developers tools. He has been using Docker since 5 years ago and thinks the container journey is just beginning. Prior that, he completed his PhD on on parallel computation and advanced compilation techniques in order to allow more declarative programming techniques.

=======================================

* **Title**: Just Enough Docker
* **Speaker**: Ramiro Berrelleza
* **Language**:es
* **Type**: Presentation 25-30 mins
* **Level**: standard
* **Tags**: devops, deployment, clusters
* **Description**: Docker democratized the container technology a few years ago. Containers are a great solution to execute processes in a portable way, and distribute these processes along different machines. On the other hand, having deployment tools based on the container as the unit of deployment introduces new challenges already solved by virtualization technology. This talk will cover these scenarios, and give the speaker point of view about the best usage of the container technology.
* **Speaker Bio**: Ramiro is Software Architect @Atlassian. He has extensive skills in computing, scalability, cloud, testing, distributed system and engineering practices. Currently interested in cloud technologies, internet of things, scalability problems and startups.

**Comment by dkapanidis** [comment]
Hi Pablo,

there are currently two meetups open 22 February, and 20 March, can you do the talk in one of those dates?

**Comment by pchico83** [comment]
20 March would work. Those dates I will have a visitor From San Francisco who is Senior Architect @Atlassian. He could complement my talk to showcase how they do to overcome the docker limitations in production. This is why I increased the duration from 35-45 minutes to 50 minutes. Is that ok?

**Comment by dkapanidis** [comment]
That's great, yes. Should I put it as one presentation or maybe we publish them as two separate talks?

**Comment by pchico83** [comment]
Sure, two separated talks sounds good. I will update the issue with two descriptions and two Bio.
Thanks!

**Comment by pchico83** [comment]
@spiddy also, how do you prefer the talks? english or spanish?
we both are spanish and english speakers

**Comment by dkapanidis** [comment]
Barcelona city hosts a lot of english-only-speaking foreigners, but there is also a number of spanish-only-speaking locals.

I try to be all-inclusive in the meetup, both for speakers and attendees. Until now I defaulted to English, but I think in this case since you both come from high-profile companies and both speak Spanish it would be a good opportunity to balance it and default to Spanish, so that we don't leave out the spanish-only-speaking locals, what do you think?

**Comment by pchico83** [comment]
@spiddy makes sense to me, thanks!

**Comment by pchico83** [comment]
@spiddy updated

**Comment by dkapanidis** [comment]
Talks are published at meetup page: https://www.meetup.com/docker-barcelona-spain/events/247733700/

can you review the intro I put if it is ok by you?

**Comment by pchico83** [comment]
@spiddy LGTM!

**Comment by dkapanidis** [comment]
@pchico83 are you on your way to eDreams?
