### ISSUE TITLE
Container-friendly Intrusion Detection with Falco

### ISSUE THREAD

**Issue by mateobur** [docker-barcelona/speakers#14]
* **Title**: Container-friendly Intrusion Detection with Falco
* **Speaker**: Mateo Burillo @mateobur
* **Language**: "es", but can be "en" if appropriate
* **Type**: Presentation
* **Level**: standard
* **Tags**: docker security, runtime security, workshop, sysdig falco

**Description**

Falco is an open source behavioral security monitor for containers. It uses Sysdig
technology to examine Linux system calls and takes advantage of the immutable and
reproducible nature of containerized apps to pinpoint anomalies. Totally transparent, with
container-specific metadata for its rules.

In this talk Mateo Burillo will summarize the container security landscape with its relatively new
strengths and attack vectors and then focus on several hands-on Falco live demos such as:

- Interactive shells running inside your containers
- Controlling writable and non-writable directories
- Access to sensitive information by unauthorized processes

**Speaker Bio** (optional)

Integrations engineer and tech writer @sysdig

Mateo greatly enjoys tinkering with container technologies, creating homebrew lab environments, and the perpetual newbie feeling of this fast moving world of tech.

He spends most of the day getting in the shoes of the user at many different levels: user interface, task automation, proper documentation and error handling, code examples, and dissecting deep technical concepts for the newcomers.

**Comment by dkapanidis** [comment]
Talk is published at https://www.meetup.com/docker-barcelona-spain/events/245156978/
