### ISSUE TITLE
InfluxDB Stack on Marathon

### ISSUE THREAD

**Issue by lbernardez5** [docker-barcelona/speakers#16]
* **Title**: InfluxDB Stack on Marathon
* **Speaker**: Oscar Muñoz, Lorena Bernardez
* **Language**: es
* **Type**: (Presentation 30-45 mins | Lightning Talk 5-10 mins)
* **Level**: (basic)
* **Tags**: monitoring

**Description**
InfluxDB is a time series database built from the ground up to handle high write and query loads. InfluxDB is meant to be used as a backing store for any use case involving large amounts of timestamped data, including DevOps monitoring, application metrics, IoT sensor data, and real-time analytics.

*Provide a small paragraph that describes your proposal*

- Introduction 
- Why influxdb?
- Custom configuration
- Deploy on Marathon infrastructure
- Migration from marathon to Kubernetes 

**Speaker Bio** (optional)

*A short bio of the speaker*

**Comment by dkapanidis** [comment]
published at https://www.meetup.com/docker-barcelona-spain/events/251511165/
