### ISSUE TITLE
IoT hackathon with Docker

### ISSUE THREAD

**Issue by pimterry** [docker-barcelona/speakers#17]
Not quite a talk, but I think this is the place to propose things.

We're planning a Resin.io hackathon in Barcelona on October 20th for around 100 people, where developers can learn how to build IoT applications with Docker, using Resin.io, Raspberry Pi's and some hardware attachments (all of which we'll provide - attendees just need a laptop).

I spoke at Docker Barcelona [last year](https://github.com/docker-barcelona/speakers/issues/9), and the audience were fantastic, full of excellent and detailed questions about the work we're doing on top of and within Docker. I'd love to see some of them there. Would you be interested in posting the hackathon as an external event in the Docker Barcelona meetup?

**Comment by pimterry** [comment]
Hi @spiddy, what do you think about this?

**Comment by pimterry** [comment]
Nevermind, the hackathon is now sold out. Let me know if you have strong feelings about hearing/not hearing about this kind of thing in future though.

**Comment by dkapanidis** [comment]
Hi Tim,

sorry for not following up on this soon enough, yes I want to hear about this kind of things in the future! and yes this channel is the correct one. Glad to hear it's sold out, I wasn't expecting anything less.

Ping me again next time
