### ISSUE TITLE
Docker Logging with the ELK Stack

### ISSUE THREAD

**Issue by DanielBerman** [docker-barcelona/speakers#4]
* **Title: Docker Logging with the ELK Stack**
* **Speaker: Daniel Berman**
* **Language: EN**
* **Type: Presentation 30-45 mins**
* **Level: Standard**
* **Category: Monitoring, logging**

**Description**
Logging remains one of the most valuable ways to troubleshoot and monitor our applications, but in software development today, the task has become extremely difficult due to the nature of modern environments. In this talk, I will details the various challenges facing developers in a microservices and Dockerized world, and how to use ELK to tackle them with centralized logging and a touch of machine learning.

*A short bio of the speaker*
Daniel is a Product Evangelist @logz.io. Daniel speaks/writes about PHP, AWS, ELK and Docker and is an organizer of several meetups and DevOpsDays Tel-Aviv. Outside work, Daniel is a family man, a runner and a Liverpool FC fan!

**Comment by dkapanidis** [comment]
are you available for speaking at 18th of May?

**Comment by dkapanidis** [comment]
closing due to lack of response, if you want to reapply to the CFP, re-open the issue.
