### ISSUE TITLE
Beekeeping for Dummies, Managing Docker Swarm

### ISSUE THREAD

**Issue by frjaraur** [docker-barcelona/speakers#5]
* **Title**:  Beekeeping for Dummies, Managing Docker Swarm
* **Speaker**:  Javier Ramírez Urea
* **Language**: es
* **Type**: Presentation 30-45 mins
* **Level**: standard
* **Tags**: Docker, Clustering

**Description**
This is a small index of what we will see.
Beekeeping for Dummies, Managing Docker Swarm.
- Swarmkit
- Legacy Swarm vs Swarm Mode
- Swarm Mode Concepts
- Swarm Mode Features in Depth with Examples
- Why Swarming?

**Provide a small paragraph that describes your proposal**

My proposal for this speach is showing people how easy is create and manage different objects using docker swarm mode.

**Speaker Bio**

Senior Consultant and Docker Instructor "Containerized"  at Hopla Software. Microservices based solutions and Performance and Monitoring Systems expert.
Hopla, company based on open source,  founded in 2013 and headquartered in Madrid has as main mission provide software tools  to medium and large companies, that allow them to grow better and faster through a more powerful and efficient data handling

**A short bio of the speaker** 

Fco. Javier Ramírez Urea, Senior Consultant and Docker Instructor "Containerized"  at Hopla Software. Microservices based solutions and Performance and Monitoring Systems expert.

**Comment by dkapanidis** [comment]
Please confirm if you attend at 18 of May meetup.

**Comment by dkapanidis** [comment]
Event is drafted here https://www.meetup.com/docker-barcelona-spain/events/239871527/

**Comment by dkapanidis** [comment]
Hi @frjaraur, are you still interested in giving this talk on the Meetup? There are available slots on December's event https://www.meetup.com/docker-barcelona-spain/events/245156833

**Comment by dkapanidis** [comment]
closing due to lack of response, if you want to reapply to the CFP, re-open the issue.
