### ISSUE TITLE
Monitoring Docker

### ISSUE THREAD

**Issue by lbernardez5** [docker-barcelona/speakers#6]
* **Title**: Monitoring docker containers
* **Speaker**: Oscar Muñoz/ Lorena Bernárdez/ Fernando Velazquez
* **Language**: en
* **Type**: (Presentation 30-45 mins )
* **Level**: basic
* **Tags**: monitoring

**Description**
We will focus on the next topics:
- How to monitor a docker status and performance
- Prometheus alerts and auto-discovery
- Prometheus relabelling

**Comment by dkapanidis** [comment]
Planned for 18th of May.
