### ISSUE TITLE
Portainer.io

### ISSUE THREAD

**Issue by deviantony** [docker-barcelona/speakers#7]
* **Title**: Manager your Docker clusters and hosts with Portainer
* **Speaker**: Anthony Lapenna
* **Language**: en 
* **Type**: Presentation 30-45 mins
* **Level**: basic
* **Tags**: management, live-demo

**Description**

Portainer.io is a software company based in Auckland, New Zealand. It offers a user interface for Docker called Portainer. This UI was born after the feeling that there was a need for IT infrastructure technicians, having no or a poor knowledge with Docker, to have a tool helping them use Docker. This is Portainer motto: keep it simple. As simple to use as it is to deploy, it allows you to manage Docker standalone hosts, Docker Swarm standalone clusters as well as Docker clusters using Swarmkit (Swarm mode). It is available on Linux, Windows & Mac. The talk will present Portainer.io and the software, it will also include a quick comparison with the existing solutions (Docker Datacenter, Shipyard...) and a feature analysis. It will end with a live demo of the software.

**Comment by dkapanidis** [comment]
Hi,

we have an event scheduled for [16th of November ](https://www.meetup.com/docker-barcelona-spain/events/244113207/) would you be available to do a presentation?

**Comment by deviantony** [comment]
Hey @spiddy 

Sure, I'd be available. Do you need anything?

**Comment by dkapanidis** [comment]
Just your presence :)

Announced talk at event: https://www.meetup.com/preview/docker-barcelona-spain/events/244113207

See you soon

**Comment by deviantony** [comment]
Awesome, see you there ! ;-)

**Comment by dkapanidis** [comment]
Just a quick follow-up. The event is on this Thursday (https://www.meetup.com/preview/docker-barcelona-spain/events/244113207) you have the stage for 45-60 mins, take as much time you need.

The event is at eDreams office (Bailen 67) you can find details on the meetup.

**Comment by dkapanidis** [comment]
Are you here?
