### ISSUE TITLE
Optimizing IoT with Multi-Stage Docker Builds

### ISSUE THREAD

**Issue by pimterry** [docker-barcelona/speakers#9]
* **Title**: Optimizing IoT with Multi-Stage Docker Builds
* **Speaker**: Tim Perry
* **Language**: en
* **Type**: Presentation 30-45 mins
* **Level**: standard
* **Tags**: multistage, docker, iot

**Description**

In Docker 17.05, a fantastic new feature quietly appeared: multi-stage builds. In this talk, we'll look at what these are, how they can improve your Docker build infrastructure, and how we at Resin.io use them to optimize containers for IoT.

**Speaker Bio** (optional)

By day, Tim Perry is a senior software engineer at Resin.io. By night, he’s also the creator of Build Focus, a contributor to a huge range of open-source tools across the JS, Java and C# ecosystems, and the maintainer of Loglevel, Git-Confirm and Server Components.

**Comment by dkapanidis** [comment]
Thanks for the entry, we'll plan soon next Docker meetups and notify you
for available slots!
ᐧ


__
Dimitris Kapanidis
Founder

T/ +34 6780 49 780



Harbur Cloud Solutions SL. - Modernizing Software Delivery
Travessera de Gracia 294 Entlo. 1, 08025, Barcelona, Spain
https://www.harbur.io

NOTICE:  This e-mail and any attachments are confidential and intended
solely for the attention and use of the named addressee(s). If you are not
the intended recipient, be aware that any disclosure, copying, distribution
or use of this e-mail or any part of it, without the prior written consent
of Harbur Cloud Solutions SL. is prohibited and may be unlawful. If you
have received this e-mail in error, please notify immediately by returning
it to the sender and delete this copy from your system.

**Comment by dkapanidis** [comment]
Hi,

we have an event scheduled for [16th of November ](https://www.meetup.com/docker-barcelona-spain/events/244113207/) would you be available to do a presentation?

**Comment by pimterry** [comment]
I'd love to, but I'm afraid I'm already super busy in November, and I won't have time. I am free for almost any date in December though, if you're planning any slots then?

**Comment by dkapanidis** [comment]
Sure, but no fixed date yet, I'll notify you when something concrete appears.

**Comment by dkapanidis** [comment]
Hi, we have a date for December, it's 14th of the month (https://www.meetup.com/docker-barcelona-spain/events/245156833) How is your availability that day for giving the talk?

**Comment by pimterry** [comment]
@spiddy, sure, thanks, that works great.

**Comment by dkapanidis** [comment]
ok, you're on.  (https://www.meetup.com/docker-barcelona-spain/events/245156833) see you on December 👍

**Comment by pimterry** [comment]
Awesome, see you then!
